version: '3'

services:

  db:
    image: postgres:9.6
    
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "6666:5432"
    volumes:
      - ./db/development-seed.sql:/docker-entrypoint-initdb.d/development-seed.sql
