version: '3'
services:
  db:
    image: postgres:9.6
    env_file: ./server/.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./development-seed.sql:/docker-entrypoint-initdb.d/development-seed.sql
