version: '3.8'

services:

  db:
    image: postgres:9.6
    
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "6666:5432"
    volumes:
      - ./db/development-seed.sql:/docker-entrypoint-initdb.d/development-seed.sql
    env_file:
      - ./server/.env
    networks: 
      - innoduel-dashboard-network

  backend:
    build: ./server
    container_name: innoduel_backend
    networks: 
      - innoduel-dashboard-network
    volumes: 
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: innoduel_frontend
    networks:
      - innoduel-dashboard-network
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    ports: 
      - "5173:5173"
    tty: true
    stdin_open: true
networks: 
  innoduel-dashboard-network:
    driver: bridge