openapi: 3.0.0
info:
  title: Innoduel API
  description: API for accessing and analyzing arenas, ideas, and voting data within the Innoduel Dashboard Application.
  version: 1.0.0
servers:
  - url: http://localhost:8000/
    description: Development server
paths:
  /api/arenas/{company_id}/arenas:
    get:
      summary: Get Arena Summaries
      description: Returns summaries for all arenas, including counts of ideas submitted, total votes, and overall win rates.
      parameters:
      - in: path
        name: company_id
        required: true
        schema:
          type: integer
        description: The unique identifier of the company to fetch arenas.
      responses:
        200:
          description: List of arena summaries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArenaSummary"
        404:
          description: No arenas found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No arenas found

  
  /api/arenas/{arena_id}:
    get:
      summary: Get Detailed Arena Information by arena_id
      description: Retrieves detailed information for a specific arena by arena_id.
      parameters:
        - in: path
          name: arena_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the arena
      responses:
        200:
          description: Detailed information of a specific arena
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArenaSummary"
        404:
          description: Arena not found

  /api/arenas/{company_id}/compare:
    get:
      summary: Compare Multiple Arenas
      description: |
        Allows for the comparison of key metrics across selected arenas using a comma-separated list of arena IDs. 
        Requires at least two arena IDs to perform the comparison.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the company associated with the arenas.
        - in: query
          name: ids
          required: true
          schema:
            type: array
            items:
              type: integer
            minItems: 2
          style: form
          explode: true
          description: |
            A list of arena IDs for comparison. The list must contain at least two IDs.
            - **style: form** and **explode: true** indicates that each value of the array will be passed as a separate parameter (e.g., `?ids=1&ids=2&ids=3`).
      responses:
        200:
          description: Comparison data for selected arenas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArenaSummary"
        404:
          description: One or more arenas not found

  /api/arenas/{company_id}/{arena_id}/ideas:
    get:
      summary: Get Detailed Ideas List for Specific Arena
      description: |
        Retrieves a detailed list of ideas for a specific arena, including votes and win rates.
        Supports sorting by 'win_rate' or 'total_votes' and filtering by a minimum vote threshold.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the company associated with the arena.
        - in: path
          name: arena_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the arena.
        - in: query
          name: sort
          schema:
            type: string
            enum: [win_rate, total_votes]
          description: |
            Specifies the sorting criterion of the ideas list.
            - 'win_rate': Sort ideas by their win rates.
            - 'total_votes': Sort ideas by their total votes.
          required: false
        - in: query
          name: order
          schema:
            type: string
            enum: [asc, desc]
          description: |
            Specifies the sorting order.
            - 'asc': Ascending order.
            - 'desc': Descending order.
          required: false
        - in: query
          name: min_votes
          schema:
            type: integer
          description: |
            Filters ideas by a minimum number of total votes. Only ideas with votes equal to or greater than this threshold will be included.
          required: false
      responses:
        200:
          description: A detailed list of ideas within the specified arena, including votes and win rates, sorted and filtered as requested.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IdeaDetail"
        404:
          description: Arena not found
          content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Arena not found

  /api/votes/{company_id}/all:
    get:
      summary: Get all votes by company ID
      description: Retrieves all votes for ideas associated with arenas owned by the specified company.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The ID of the company to retrieve votes for.
      responses:
        200:
          description: A list of votes for the specified company
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vote'
        404:
          description: No votes found for the specified company

  /api/votes/{company_id}/distribution:
    get:
      summary: Get Vote Distribution for All Arenas
      description: Retrieves vote distributions across all arenas for a given company.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The ID of the company to retrieve vote distributions for.
      responses:
        200:
          description: Vote distribution data for all arenas associated with the given company.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VoteDistributions'
        404:
          description: No ideas found for the given company_id

  /api/votes/{company_id}/{arena_id}/distribution:
    get:
      summary: Get Vote Distribution for All Arenas
      description: Retrieves vote distributions across all arenas for a given company.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The ID of the company to retrieve vote distributions for.
        - in: path
          name: arena_id
          required: true
          schema:
            type: integer
          description: The ID of the arena to retrieve vote distributions for.
      responses:
        200:
          description: Vote distribution data for all arenas associated with the given company.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VoteDistributions'
        404:
          description: No ideas found for the given company_id
  
  /api/votes/{company_id}/{arena_ids}/distribution/compare:
    get:
      summary: Compare Vote Distribution Across Multiple Arenas
      description: |
        Retrieves and compares vote distribution across selected arenas within a specific company.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The ID of the company for which to compare vote distribution across arenas.
        - in: query
          name: arena_ids
          required: true
          schema:
            type: array
            tems:
              type: integer
            minItems: 2
          style: form
          explode: true
          description: |
            Comma-separated list or array of arena IDs for which to compare vote distribution. A minimum of two arena IDs are required to perform the comparison.
      responses:
        200:
          description: Vote distribution comparison data for selected arenas
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_votes_across_arenas:
                    type: integer
                    description: The total number of votes across all specified arenas.
                  vote_distribution_per_idea:
                    type: array
                    items:
                      $ref: "#/components/schemas/VoteDistributions"
        404:
          description: One or more arenas not found


  /api/arenas/{company_id}/{arena_id}/win_rate/trends:
    get:
      summary: Win Rate Trends for Specific Arena
      description: Visualizes the win rate trends of top ideas over time within a specific arena.
      parameters:
        - in: path
          name: company_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the company associated with the arena
        - in: path
          name: arena_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the arena
      responses:
        200:
          description: Win rate trend data for the specified arena
          content:
            application/json:
              schema:
                type: object
                properties:
                  arena_id:
                    type: integer
                  trends:
                    type: array
                    items:
                      type: object
                      properties:
                        idea_id:
                          type: integer
                        winRateOverTime:
                          type: array
                          items:
                            type: object
                            properties:
                              timestamp:
                                type: string
                                format: date-time
                              winRate:
                                type: string
        404:
          description: Arena not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Arena not found

components:
  schemas:
    ArenaSummary:
      type: object
      properties:
        arena_id:
          type: integer
        total_ideas:
          type: integer
        total_votes:
          type: integer
        overall_win_rate:
          type: string
    
    Vote:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        idea_id:
          type: integer
        win:
          type: boolean
        created:
          type: string
          format: date-time
        idea:
          type: object
          properties:
            id:
              type: integer
            idea_text:
              type: string
            arena:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
        user_info:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string

    VoteDistributions:
      type: object
      properties:
        total_votes:
          type: integer
          description: The total number of votes.
        vote_distributions:
          type: array
          items:
            $ref: '#/components/schemas/VoteDistribution'
    VoteDistribution:
      type: object
      properties:
        idea_id:
          type: integer
          description: The ID of the idea.
        idea_text:
          type: string
          description: The text of the idea.
        arena_id:
          type: integer
          description: The ID of the arena that the idea belongs to.
        arena_name:
          type: string
          description: The name of the arena.
        total_votes:
          type: integer
          description: The total number of votes for the idea.

    IdeaDetail:
      type: object
      properties:
        idea_id:
          type: integer
          description: The unique identifier of the idea.
          example: 1
        idea_text:
          type: string
          description: The text of the idea submitted to the arena.
          example: "Implement a new voting system."
        win_rate:
          type: string
          description: The win rate of the idea, expressed as a percentage.
          example: "75%"
        total_votes:
          type: integer
          description: The total number of votes this idea has received.
          example: 150
        created_at:
          type: string
          format: date-time
          description: The timestamp when the idea was submitted.
          example: "2023-01-01T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the idea was last updated.
          example: "2023-01-02T12:00:00Z"
        tags:
          type: array
          items:
            type: string
          description: A list of tags associated with the idea for categorization or filtering.
          example: ["innovation", "voting"]
        comments_count:
          type: integer
          description: The number of comments made on the idea.
          example: 25
        author:
          type: object
          properties:
            user_id:
              type: integer
              description: The unique identifier of the idea's author.
              example: 42
            username:
              type: string
              description: The username of the idea's author.
              example: "idea_creator"
      required:
        - idea_id
        - idea_text
        - win_rate
        - total_votes

